
services:

  devopsdb:
    image: anjaligundavaram/docker-jenkins:vprofile-db-secondone
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  application:
    image: anjaligundavaram/docker-jenkins:vprofile-app-newone
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

